server:
  http_listen_port: 9080
  grpc_listen_port: 9095

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/api/prom/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log

    pipeline_stages:
      - json:
          expressions:
            log: log
      - regex:
          expression: '^(?P<timestamp>[^ ]*) (?P<level>[^ ]*) (?P<msg>.*)$'
